apiVersion: v1
kind: Service
metadata:
  name: biodiversity-maplibre
  labels:
    app: biodiversity-maplibre
spec:
  type: ClusterIP
  selector:
    app: biodiversity-maplibre
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
