apiVersion: v1
kind: Service
metadata:
  name: ca-lands
  labels:
    app: ca-lands
spec:
  type: ClusterIP
  selector:
    app: ca-lands
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
