apiVersion: v1
kind: Service
metadata:
  name: padus
  labels:
    app: padus
spec:
  type: ClusterIP
  selector:
    app: padus
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
